services:
  serve:
    image: mdbook
    build:
      context: .
      dockerfile: deploy/mdbook.dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    develop:
      watch:
        - path: theme/
          action: sync+restart
        - path: book.toml
          action: sync+restart
        - path: extra-style.css
          action: sync+restart
        - path: src/
          target: /book/src
          action: sync
