[package]
name = "wgpu-tutor-src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
winit = "0.27"
wgpu = "0.14"
pollster = "0.2"
anyhow = "1"
