name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.12'
      
      - run: "curl -s https://api.github.com/repos/Michael-F-Bryan/mdbook-linkcheck/releases/latest \\\
              | grep browser_download_url \\\
              | grep $(rustc -Vv | grep host | cut -d' ' -f2) \\\
              | cut -d : -f 2,3 \\\
              | tr -d \\\" \\\
              | wget -qi -"

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.UPLOAD_TOKEN }}
          publish_dir: ./book/html
          publish_branch: main
          destination_dir: wgpu-tutor
          external_repository: switefaster/switefaster.github.io
