name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container: michaelfbryan/mdbook-docker-image
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - run: mdbook build

      - run: sudo apt-get update & sudo apt-get install git

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.UPLOAD_TOKEN }}
          publish_dir: ./book/html
          publish_branch: main
          destination_dir: wgpu-tutor
          external_repository: switefaster/switefaster.github.io
